# Update the path to this CONFIG.yaml file in function load_config of module train.py

PATH :
  DATA_DIR : "/home/colind/work/Mines/TR_DIMA/DIMA_code/data"

DATA :
  TOTAL_N_CHANNELS : 111
  NUMBER_OF_CHANNELS : "all" # 25 # "all"
  BALANCE : 0.2 # False # proportion of sick pixels after transformation. no balance : False
  TEST_SIZE : 0.2  # for random train/test split
  BATCH_SIZE : 1000  # all data all at once : null
  TEST_LEAVES : [15, 16, 17]
  NUMBER_OF_LEAVES : 17

TRAINING_INFO :
  # for Neural Network
  NUM_EPOCHS : 500
  HIDDEN_SIZE : "HALF"  # "HALF" : number_of_features // 2 ; "INPUT" : number_of_features
  LEARNING_RATE : 0.07
  # for decision tree
  MAX_DEPTH : 6  # For no limit : null
  CHANNELS : [15, 27, 80, 100]